name: CI Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 6"

jobs:
  black-format:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --diff"
          src: "./src ./tests"

  flake8-lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: flake8 Lint
        uses: py-actions/flake8@v2

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout Zipline
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install TA-Lib Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo ./tools/install_talib.sh

      - name: Install Zipline
        run: |
          python -VV
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install tox tox-gh-actions
          python -m pip install .[test]

      - name: Unittests with tox & pytest
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 90
          max_attempts: 3
          retry_on: error
          new_command_on_retry: python -m pip install tox tox-gh-actions .[test]
          command: tox
