name: CI Tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10]

    steps:
      - name: Checkout Zipline
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install TA-Lib Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          curl -L -o ta-lib-0.4.0-src.tar.gz  http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz &&
          tar xvfz ta-lib-0.4.0-src.tar.gz &&
          cd ta-lib &&
          ./configure &&
          sudo make &&
          sudo make install &&
          sudo ldconfig

      - name: Install Zipline
        run: |
          python -VV
          python -m pip install --upgrade pip setuptools wheel
          pip install tox tox-gh-actions
          pip install -e .[test]

      - name: Lint with flake8
        run: |
          flake8

      - name: Unittests with tox & pytest
        run: |
          tox -e py310-pandas15

      - name: Upload coverage data to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          name: codecov-umbrella
          verbose: true
