name: Anaconda

on:
  workflow_dispatch

jobs:
  build_wheels:
    name: py${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      MACOSX_DEPLOYMENT_TARGET: 10.15
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python: [ '3.10' ]

    steps:
      - name: Checkout zipline-crypto
        uses: actions/checkout@v2

      - name: Setup miniconda3
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          channel-priority: strict
          mamba-version: "*"
          python-version: ${{ matrix.python }}
          activate-environment: recipe
          channels: ml4t, conda-forge, defaults, anaconda, ranaroussi, adteam

      - name: create uploader
        # address broken client under py3.10
        if: ${{ matrix.python == '3.10' }}
        run: conda create -n up python=3.7 anaconda-client

      - name: conda build for ${{ matrix.os }}
        run: |
          conda activate recipe
          mamba install -n recipe boa conda-verify anaconda-client
          conda mambabuild --output-folder . --python ${{ matrix.python }} conda/zipline-crypto

      - name: activate uploader
        # address broken client under py3.10
        if: ${{ matrix.python == '3.10' }}
        run: conda activate up

      - name: store linux result
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          path: linux-64/*.tar.bz2

      - name: upload linux
        if: ${{ matrix.os  == 'ubuntu-latest' }}
        run: anaconda upload -l main -u ml4t linux-64/*.tar.bz2
